name: Slack Notifications

on:
  pull_request:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: CI Test Result in Slack
      uses: sanjaykrishnanrs/slack-notify-junitxml-action@0.1.0-beta
      with:
        title: TP_Devops Tests
        slackbotid: ${{secrets.SLACKBOTID }}
        slackbottoken: ${{secrets.SLACKBOTTOKEN}}
        slackchannel: ${{ secrets.SLACKCHANNEL}}
